### ISSUE TITLE
Regarding the addition of other video datasets

### ISSUE THREAD

**Issue by mary-0830** [open-compass/VLMEvalKit#334]
Hello author, thank you very much for providing evaluations related to videos. Are there any plans to add datasets like ActivityNetQA and MSVDQA for video evaluations in the future?

Thanks for your reply.

**Comment by kennymckormick** [comment]
Hi, @mary-0830 , 
We do not have plans for supporting MSVDQA  / ActivityNetQA, since the quality of those benchmarks are unsatisfactory (we have mentioned some reasons in the MMBench-Video tech report: https://arxiv.org/pdf/2406.14515). Meanwhlie, we do have plans to support more video benchmarks in VLMEvalKit, which may includes MVBench,  TempCompass, and others

**Comment by mary-0830** [comment]
> Hi, @mary-0830 , We do not have plans for supporting MSVDQA / ActivityNetQA, since the quality of those benchmarks are unsatisfactory (we have mentioned some reasons in the MMBench-Video tech report: https://arxiv.org/pdf/2406.14515). Meanwhlie, we do have plans to support more video benchmarks in VLMEvalKit, which may includes MVBench, TempCompass, and others

okay, i see!
