### ISSUE TITLE
The performance of Cambrian-1-8B.

### ISSUE THREAD

**Issue by Haochen-Wang409** [open-compass/VLMEvalKit#439]
Hello, I am using this code to evaluate the official checkpoint of Cambrian-1-8B. However, I fail to reproduce the results. Specifically, I got only 64.78 on MMBench-DEV-EN, while the reported score is 75.9 (Table 8 of the paper).

Could you help me to reproduce the results?

**Comment by PhoenixZ810** [comment]
Hi,

Thank you for your findings! We have identified that the issue is due to Cambrian-8b’s instruction-following capabilities. We recommend modifying the prompt in [MMBench](https://github.com/open-compass/VLMEvalKit/blob/1e2c6bb20a9803552d8bd56d5cb0ce876ae2a648/vlmeval/dataset/image_mcq.py#L171) as follows:

```
if len(options):
    prompt += options_prompt
    # prompt += 'Please select the correct answer from the options above. \n'
    prompt +=  '\n' + "Answer with the option's letter from the given choices directly."
```
With this change, the evaluation results of MMBench-Dev-EN for Cambrian-8B should improve to **76.29**.

Best regards.

**Comment by Haochen-Wang409** [comment]
Thanks for the reply! I have successfully reproduced the results!
