### ISSUE TITLE
The evaluation result were all wrong after upgrade

### ISSUE THREAD

**Issue by MonolithFoundation** [open-compass/VLMEvalKit#503]
the evaluation got far worse metric after uprade, what could going wrong?

My code didn't change anything.

**Comment by MonolithFoundation** [comment]
That's wired, MMBench_DEV_CN, and MMStar, same model, previous evaluted as 95.8 and 56 repectively, but using latest vlmeval, the result got 79 and 48, the result far more lower,

Any reason for this?

**Comment by kennymckormick** [comment]
> That's wired, MMBench_DEV_CN, and MMStar, same model, previous evaluted as 95.8 and 56 repectively, but using latest vlmeval, the result got 79 and 48, the result far more lower,
> 
> Any reason for this?

The previous results look weird: AFAIK, the latest state-of-the-art VLM can not achieve 90+% Acc on MMBench-DEV. Would you please provide the specific commit id you previously used so that  I can try to reproduce the error.

**Comment by MonolithFoundation** [comment]
We intended to do this, to remove possibility of model issue, we let MMBench_DEV_CN trained in dataset. So it's extremly weired so low evaluation metric on DEV datasets. (MMStar not trained, but our score previous is normal, not normal after changed evaluation pipline as well)

**Comment by kennymckormick** [comment]
I have re-evaluated MMBench_DEV_CN and MMStar on multiple VLMs (which are evaluated more than half a year ago) with the latest code, including:

GPT4V_20240409, qwen_chat, llava_v1.5_7b, llava_v1.5_13b, deepseek_vl_7b, deepseek_vl_1.3b. 

Basically, all evaluation results align with the accuracies we reported on Open VLM Leaderboard, with the maximum accuracy difference less than 2% (since there is some small changes about the choice extractor: gpt-3.5-0613 is no longer supported by OpenAI so we switch to gpt-3.5-0125). 
Moreover, we have provided all prediction files at: https://huggingface.co/datasets/VLMEval/OpenVLMRecords for user comparisons. 

If you want to go further with this issue, please provide an officially supported DATASET x MODEL pair, which you find the evaluation result is significantly different from our reported one. Also, a friendly reminder is, slight changes in the environment (for example, the version of some python packages) may also significantly affect the performance of your custom model. One can try to detect it by comparing old & new predictions.

**Comment by MonolithFoundation** [comment]
Oh, sorry for my mistake, it's normal now!

**Comment by ZI-MA** [comment]
> Oh, sorry for my mistake, it's normal now!哦，抱歉，我的错误，现在已经正常了！

Could you teach me how to solve it?
