### ISSUE TITLE
Enhancing Multi-Choice Question Handling with Case-Sensitive Matching

### ISSUE THREAD

**Issue by jdy18** [open-compass/VLMEvalKit#99]
It might be beneficial to implement a mechanism for exact matching of uppercase option letters in multi-choice questions. This could help avoid confusion caused by the presence of quantifiers like "a" in responses, which might be mistakenly interpreted as indicating multiple choices. Additionally, in cases where multiple letters or multiple instances of "yes"/"no" appear, the system could prioritize the analysis of the first word in the sentence to determine the intended response.

I am also curious about whether the scores currently displayed on the OpenCompass leaderboard have been updated to reflect these latest modifications. Could you provide any information on this?

**Comment by kennymckormick** [comment]
Hi, @jdy18 ,
For the ideas you proposed,
1. Upper case matching: We are not going to implement it, since the choice labels can also appear as lowercase letters, while quantifiers like "a" can also appear as uppercase letters (when it appears at the beginning of a sentence). Thus implementation may lead to noisy evaluation results. So it would be better to employ the LLM-based matching for these ambiguous cases.
2. Same, the first word may not indicate the actual yes / no label.
3. Yes.
